export const MessageNotice = {
  loginSuccess: "Đăng nhập thành công",
  loginFailed: "Tên đăng nhập hoặc mật khẩu không chính xác",
  loginFailed2: "Đăng nhập thất bại",
  loginFailed3: "Có lỗi trong quá trình đăng nhập",
  RegisterSuccess: "Đăng kí thành công",
  Error500: "Gặp vấn đề quá trình lấy dữ liệu",
  CreateAddressSuccess: "Tạo địa chỉ mới thành công",
  UpdateAddressSuccess: "Cập nhật địa chỉ thành công",
  CreateOrderFailed: "Xảy ra lỗi trong quá trình tạo thanh toán",
  CreateVnpayFailed: "Khởi tạo vnpay lỗi",
  OutOfStock: "Sản phẩm hiện không còn",
  AddProductToCartSuccess: "Thêm sản phẩm thành công",
  CancelOrderSuccess: "Đơn hàng đã được hủy thành công",
  CancelOrderSuccess2:
    "Đơn hàng invoiceCode đã bị hủy do quá hạn thời gian thanh toán",
  CancelOrderFailed: "Có lỗi xảy ra khi hủy đơn hàng",
  ReasonCancel: "Đơn hàng đã bị hủy do quá hạn thời gian thanh toán",
  RequestWarrantySuccess: "Tạo bảo hành thành công",
  FavouriteSucces: "Thêm vào danh sách yêu thích thành công",
  FavouriteFailed: "Bỏ yêu thích thất bại",
  InvalidRole: "Tài khoản có vai trò không phù hợp",
  ForgotAddress: "Bạn chưa chọn địa chỉ giao hàng",
  ForgotAddToCart: "Bạn chưa có hàng trong giỏ",
};

export const AdminMessageNotice = {
  UpdateRoleSuccess: "Cập nhật chức vụ thành công",
  AddEmployeeSuccess: "Thêm nhân viên thành công",
  AddEmployeeFailed: "Có lỗi trong quá trình thêm nhân viên",
  BanFailed: "Xảy ra lỗi trong quá trình chặn",
  UnBanFailed: "Xảy ra lỗi trong quá trình mở chặn",
  BanOrUnbanSuccess: "Cập nhật trạng thái thành công",
  UpdateFailed: "Có lỗi trong quá trình cập nhât",
  GetBlogFailed: "Có lỗi trong quá trình lấy tin tức",
  UpdateSuccess: "Cập nhật thành công",
  AddBlogSucces: "Thêm tin tức mới thành công",
  AddBlogFailed: "Xảy ra lỗi trong quá trình thêm tin tức",
  HideNews: "Ẩn tin tức thành công",
  HideNewsError: "Gặp lỗi trong quá trình ẩn tin tức",
  AbleNews: "Hiện tin tức thành công",
  AbleNewsError: "Gặp lỗi trong quá trình hiện tin tức",
  UpdateStatusSucces: "Cập nhật trạng thái thành công",
  UpdateStatusFailed: "Lỗi cập nhật trạng thái",
  AddBrandSuccess: "Thêm thương hiệu thành công",
  AddBrandFailed: "Xảy ra lỗi trong quá trình thêm",
  AddCategory: "Thêm loại máy thành công",
  AddCategoryFailed: "Xảy ra lỗi thêm loại máy",
  AddMachineComponent: "Thêm bộ phận máy thành công",
  FailMachineComponent: "Xảy ra lỗi trong quá trình thêm bộ phận máy",
  AddCategoryNews: "Thêm loại tin tức thành công",
  OrderUpdateSuccess: "Cập nhật đơn hàng thành công",
  OrderUpdateFailed: "Cập nhật đơn hàng thất bại",
  CreatTaskSuccess: "Giao nhiệm vụ thành công",
  CreatTaskFailed: "Giao nhiệm vụ thất bại",
  AddSucces: "Thêm mới thành công",
  ForgetAddComponent: "Thêm bộ phận máy",
  AddMachinerySuccess: "Thêm máy thành công",
  AddMachineryFailed: "Xảy ra lỗi trong quá trình thêm máy",
  AddMachineToBarn: "Thêm máy vào kho",
  AddRankSuccess: "Thêm hạng thành công",
  AddRankCustomerSuccess: "Thăng hạng người dùng thành công",
  SuccessAddQuantity: "Thêm số lượng chi tiết thành công",
  FailAddQuantity: "Xảy ra lỗi trong lúc thêm số lượng chi tiết ",
  ErrorSerialAdd: "Xảy ra lỗi trong quá trình thêm số lượng máy",
  AddSerialSuccess: "Thêm số lượng máy mới thành công",
  CreateDiscount: "Tạo chương trình giảm giá thành công",
  UpdateDiscount: "Cập nhật Chương trình giảm giá thành công",
  OpenDiscount: "Mở lại chương trình giảm giá thành công",
  CloseDiscount: "Đóng lại chương trình giảm giá thành công",
  ErrorDiscount: "Xảy ra lỗi",
  ErrorGet: "Xảy ra lỗi",
  ErrorUpdate: "Xảy ra lỗi trong quá trình cập nhật",
  ErrorDelete: "Xảy ra lỗi trong quá trình xoá",
  SellingPriceMoreThanStockPrice: "Giá bán phải hơn giá nhập",
  ForgotExecutionDate: "Chọn ngày đi làm nhiệm vụ",
  DiscountCategories: "Chọn ít nhất 1 loại máy",
  DiscountCategoriesSuccess: "Thêm loại máy cho giảm giá thành công",
  DiscountCategoriesFailed:
    "Xảy ra lỗi trong quá trình thêm loại máy cho giảm giá ",
  GetUserError: "Lỗi lấy thông tin người dùng",
};
